# Usa una imagen base de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el script de procesamiento al contenedor
COPY split_processing.py .

# Instalar las dependencias necesarias
RUN pip install pandas numpy scipy

# Comando por defecto para ejecutar el script
CMD ["python", "split_processing.py"]