# Dockerfile

# Usar una imagen base ligera de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el script Python al contenedor
COPY split_dataframe.py .

# Instalar las dependencias necesarias
RUN pip install pandas numpy

# Ejecutar el script al iniciar el contenedor
CMD ["python", "split_dataframe.py"]